import Image from 'next/image'
import React from 'react'
import jlImg from '../public/jobsjl.svg'
import HeaderLink from '@/components/HeaderLink'
import ExploreIcon from '@mui/icons-material/Explore'
import GroupIcon from '@mui/icons-material/Group'
import OndemandVideoIcon from '@mui/icons-material/OndemandVideo'
import BusinessCenterIcon from '@mui/icons-material/BusinessCenter';
import ArrowForwardIosRoundedIcon from '@mui/icons-material/ArrowForwardIosRounded';
import Head from 'next/head'
import { getProviders, signIn } from "next-auth/react";

function Home({providers}) {
  return (
    <div className='space-y-10'>
        <Head>
            <title>Jobs jl</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/jlsq.svg" />
        </Head>
        <header className='flex justify-around items-center py-4'>
            <div className='relative w-36 h-10'>
                <Image src={jlImg} 
                layout='fill' 
                objectFit='contain' 
                alt='/' 
                />
            </div>
            <div className='flex items-center sm:divide-x divide-gray-300'>
                <div className='hidden sm:flex space-x-8 pr-4'>
                    <HeaderLink Icon={ExploreIcon} text='Discover' />
                    <HeaderLink Icon={GroupIcon} text='People' />
                    <HeaderLink Icon={OndemandVideoIcon} text='Learning' />
                    <HeaderLink Icon={BusinessCenterIcon} text='Jobs' />
                </div>
                {Object.values(providers).map((provider) => (
                <div key={provider.name}>
                    <div className="pl-4">
                        <button
                        className="text-blue-700 font-semibold rounded-full border border-blue-700 px-5 py-1.5 transition-all hover:border-2"
                        onClick={() => signIn(provider.id, { callbackUrl: "/" })}
                        >
                        Sign in
                        </button>
                    </div>
                </div>
                ))}
            </div>
        </header>
        <main className='flex flex-col xl:flex-row items-center max-w-screen-lg mx-auto'>
            <div className='space-y-6 xl:space-y-10'>
                <h1 className='text-3xl md:text-5xl text-amber-800
                max-w-xl !leading-snug'>
                    Welcome to Jobs jl,<br/> Your Professional Community
                </h1>
                <div className='space-y-4'>
                    <div className='intent'>
                        <h2 className='text-xl'>
                            Search For a Job
                        </h2>
                        <ArrowForwardIosRoundedIcon 
                        className='text-gray-700'/>
                    </div>
                    <div className='intent'>
                        <h2 className='text-xl'>
                            Find a Person With the Same Interest
                        </h2>
                        <ArrowForwardIosRoundedIcon 
                        className='text-gray-700'/>
                    </div>
                    <div className='intent'>
                        <h2 className='text-xl'>
                            Learn a New Skill
                        </h2>
                        <ArrowForwardIosRoundedIcon 
                        className='text-gray-700'/>
                    </div>
                </div>
            </div>

            <div className='relative xl:absolute w-80 h-80 xl:w-[650px] xl:h-[650px] top-20 right-5'>
                <img src='https://rb.gy/vkzpzt' layout='fill' priority />
            </div>

        </main>
    </div>
  )
}

export default Home

export async function getServerSideProps(context) {
    const providers = await getProviders();
  
    return {
      props: {
        providers,
      },
    };
  }